filebeat.prospectors:
- input_type: log
  paths: ["logs/*.log","y:/path/to/app-logs.log"]
  json.message_key: message
  json.keys_under_root: true
  fields:
        tags: ['json']

output.elasticsearch:
  hosts: ["nagdom.domain.com:9200"]
  template.name: alertsense
  template.path: filebeat.template.json